Vagrant::Config.run do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos"

  config.vm.forward_port("web", 80, 8080)

  # Boot with a GUI so you can see the screen. (Default is headless)
  config.vm.boot_mode = :gui

  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "thenags.pp"
  end

end
